services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_DB: 'auth'
      POSTGRES_USER: 'henshi'
      POSTGRES_PASSWORD: 'henshi'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - apps

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    command: redis-server --requirepass henshi
    volumes:
      - redis:/data
    networks:
      - apps

  nginx:
    build:
      context: infra/nginx
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - UI=host.docker.internal
      - UI_PORT=4200
      - AUTH_SERVICE=host.docker.internal
      - AUTH_SERVICE_PORT=3000
      - USERS_SERVICE=host.docker.internal
      - USERS_SERVICE_PORT=3010
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - apps

volumes:
  postgres:
  redis:

networks:
  apps:
    driver: bridge
